name: talker_persistent
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  talker: ^4.8.2
  path: ^1.8.0
  hive_ce: ^2.11.3
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.4.15
  hive_ce_generator: ^1.9.2
  lints: ^5.0.0
  test: ^1.24.0
