name: talker_persistent
description: Uma extensão para o pacote talker que adiciona persistência aos logs, permitindo salvar logs tanto em arquivo quanto em banco de dados Hive.
version: 1.0.0
repository: https://github.com/seu_usuario/talker_persistent
homepage: https://github.com/seu_usuario/talker_persistent
issue_tracker: https://github.com/seu_usuario/talker_persistent/issues

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  talker: any
  path: any
  hive_ce: any
  collection: any

dev_dependencies:
  build_runner: ^2.4.15
  hive_ce_generator: ^1.9.2
  lints: ^5.0.0
  test: ^1.24.0
